//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ncqrs.Eventing.Storage.JOliver.SqlPersistence {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonSqlStatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonSqlStatements() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ncqrs.Eventing.Storage.JOliver.SqlPersistence.CommonSqlStatements", typeof(CommonSqlStatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT StreamId, StreamRevision, Commits.CommitId, CommitSequence, CommitStamp, Headers, Payload
        ///, SequentialId  FROM Commits
        /// INNER JOIN CommitSequence ON Commits.CommitId = CommitSequence.CommitId WHERE SequentialId &gt;= @SequentialId ORDER BY SequentialId ASC.
        /// </summary>
        internal static string GetCommitsAfter {
            get {
                return ResourceManager.GetString("GetCommitsAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT TOP 1 SequentialId FROM PipelineState WHERE PipelineName = @PipelineName ORDER BY SequentialId DESC.
        /// </summary>
        internal static string GetLastProcessedCommit {
            get {
                return ResourceManager.GetString("GetLastProcessedCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INSERT INTO PipelineState (PipelineName, SequentialId) VALUES (@PipelineName, (SELECT SequentialId FROM CommitSequence WHERE CommitId = @CommitId)).
        /// </summary>
        internal static string MarkLastProcessedCommit {
            get {
                return ResourceManager.GetString("MarkLastProcessedCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INSERT INTO CommitSequence (CommitId) VALUES (@CommitId).
        /// </summary>
        internal static string RegisterSequentialId {
            get {
                return ResourceManager.GetString("RegisterSequentialId", resourceCulture);
            }
        }
    }
}
