//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.CommandService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommandService.IMyNotesCommandService")]
    public interface IMyNotesCommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyNotesCommandService/CreateNewNote", ReplyAction="http://tempuri.org/IMyNotesCommandService/CreateNewNoteResponse")]
        void CreateNewNote(Commands.CreateNewNote command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyNotesCommandService/ChangeNoteText", ReplyAction="http://tempuri.org/IMyNotesCommandService/ChangeNoteTextResponse")]
        void ChangeNoteText(Commands.ChangeNoteText command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyNotesCommandServiceChannel : Website.CommandService.IMyNotesCommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyNotesCommandServiceClient : System.ServiceModel.ClientBase<Website.CommandService.IMyNotesCommandService>, Website.CommandService.IMyNotesCommandService {
        
        public MyNotesCommandServiceClient() {
        }
        
        public MyNotesCommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyNotesCommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyNotesCommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyNotesCommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateNewNote(Commands.CreateNewNote command) {
            base.Channel.CreateNewNote(command);
        }
        
        public void ChangeNoteText(Commands.ChangeNoteText command) {
            base.Channel.ChangeNoteText(command);
        }
    }
}
