using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Ncqrs")]
[assembly: AssemblyDescriptionAttribute("The CQRS Framework for .NET")]
[assembly: AssemblyVersionAttribute("0.8.0")]
[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2010, Ncqrs.org")]
[assembly: InternalsVisibleToAttribute("Ncqrs.Tests")]
[assembly: InternalsVisibleToAttribute("Ncqrs.Spec")]

