using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Ncqrs")]
[assembly: AssemblyDescriptionAttribute("The CQRS Framework for .NET")]
[assembly: AssemblyVersionAttribute("0.8.0")]
[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2010, Ncqrs.org")]
[assembly: InternalsVisibleToAttribute("Ncqrs.Tests")]
[assembly: InternalsVisibleToAttribute("Ncqrs.Spec")]

