@echo off
echo Copying framework bins
md "..\bin\Debug\"
copy "Framework\Ncqrs.CommandHandling\bin\Debug\Ncqrs.CommandHandling.dll" "..\bin\Debug\"
copy "Framework\Ncqrs.CommandHandling\bin\Debug\Ncqrs.CommandHandling.pdb" "..\bin\Debug\"
copy "Framework\Ncqrs.CommandHandling\bin\Debug\Ncqrs.CommandHandling.XML" "..\bin\Debug\"
copy "Framework\Ncqrs.Commands\bin\Debug\Ncqrs.Commands.dll" "..\bin\Debug\"
copy "Framework\Ncqrs.Commands\bin\Debug\Ncqrs.Commands.pdb" "..\bin\Debug\"
copy "Framework\Ncqrs.Commands\bin\Debug\Ncqrs.Commands.XML" "..\bin\Debug\"
copy "Framework\Ncqrs.Denormalization\bin\Debug\Ncqrs.Denormalization.dll" "..\bin\Debug\"
copy "Framework\Ncqrs.Denormalization\bin\Debug\Ncqrs.Denormalization.pdb" "..\bin\Debug\"
copy "Framework\Ncqrs.Denormalization\bin\Debug\Ncqrs.Denormalization.XML" "..\bin\Debug\"
copy "Framework\Ncqrs.Domain\bin\Debug\Ncqrs.Domain.dll" "..\bin\Debug\"
copy "Framework\Ncqrs.Domain\bin\Debug\Ncqrs.Domain.pdb" "..\bin\Debug\"
copy "Framework\Ncqrs.Domain\bin\Debug\Ncqrs.Domain.XML" "..\bin\Debug\"
copy "Framework\Ncqrs.Eventing\bin\Debug\Ncqrs.Eventing.dll" "..\bin\Debug\"
copy "Framework\Ncqrs.Eventing\bin\Debug\Ncqrs.Eventing.pdb" "..\bin\Debug\"
copy "Framework\Ncqrs.Eventing\bin\Debug\Ncqrs.Eventing.XML" "..\bin\Debug\"
copy "Framework\Ncqrs.Eventing.Bus\bin\Debug\Ncqrs.Eventing.Bus.dll" "..\bin\Debug\"
copy "Framework\Ncqrs.Eventing.Bus\bin\Debug\Ncqrs.Eventing.Bus.pdb" "..\bin\Debug\"
copy "Framework\Ncqrs.Eventing.Bus\bin\Debug\Ncqrs.Eventing.Bus.XML" "..\bin\Debug\"
copy "Framework\Ncqrs.Eventing.Storage.MongoDB\bin\Debug\Ncqrs.Eventing.Storage.MongoDB.dll" "..\bin\Debug\"
copy "Framework\Ncqrs.Eventing.Storage.MongoDB\bin\Debug\Ncqrs.Eventing.Storage.MongoDB.pdb" "..\bin\Debug\"
copy "Framework\Ncqrs.Eventing.Storage.MongoDB\bin\Debug\Ncqrs.Eventing.Storage.MongoDB.XML" "..\bin\Debug\"